/* 
 * Makerel API
 *
 * This is part of Makerel API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Koudenpa.Mackerel.Api.Client.OpenAPIDateConverter;

namespace Koudenpa.Mackerel.Api.Model
{
    /// <summary>
    /// Id
    /// </summary>
    [DataContract]
    public partial class Id :  IEquatable<Id>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Id" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Id() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Id" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        public Id(string id = default(string))
        {
            // to ensure "id" is required (not null)
            this._Id = id ?? throw new ArgumentNullException("id is a required property for Id and cannot be null");;
        }
        
        /// <summary>
        /// Gets or Sets _Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string _Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Id {\n");
            sb.Append("  _Id: ").Append(_Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Id);
        }

        /// <summary>
        /// Returns true if Id instances are equal
        /// </summary>
        /// <param name="input">Instance of Id to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Id input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Id == input._Id ||
                    (this._Id != null &&
                    this._Id.Equals(input._Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Id != null)
                    hashCode = hashCode * 59 + this._Id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
